[Work-in-Progress] Endpoints to allow downloading reports as CSV (#288)
djaodjin/djaodjin-saas pull request #291
Opened 2023-12-11 12:16 UTC by Deep-Chill

Added endpoints to allow downloading reports as CSV.

Some reports need their data to be slightly transformed, eg. balances-due view requires accounting for different units, the coupon_uses view requires accounting for nested values.

Notes:
- Works with query parameters.
- Tried the content-type approach with the request header sending Accept:text/csv but that didn't work with DRF, I think it could work with a custom CSV renderer.

2023-12-12 10:04 UTC, Deep-Chill commented
Added #289 here because it uses the Mixin created in #288 and #290 was a minor change. Not sure if the download views/URLs belong with the API views/URLs, let me know if you want them moved to 'urls/views'.

2023-12-12 17:52 UTC, smirolo requested changes
Needs to follow current code pattern for API/Download implementation.

2023-12-12 17:52 UTC, smirolo commented on saas/mixins.py
> +class CSVWriterMixin:
Why define a `CSVWriteMixin` instead of using `CSVDownloadView`?

2023-12-12 17:52 UTC, smirolo commented on saas/api/metrics.py
> +    def retrieve_metrics(self, date_periods):
It seems the `retrieve_metrics` shouldn't be redefined (as a copy/paste of the API version) but rather a `BalancesMetricsMixin` should be extracted out of `BalancesAPIView` that can be used for both, the API and Download.

2023-12-19 17:18 UTC, smirolo reviewed
Need to discuss some of the choices around returned results by `get_queryset`.

2023-12-19 17:18 UTC, smirolo commented on saas/api/metrics.py
> +    def retrieve_metrics(self, request):
Seems to be missing a blank line above the method definition.

2023-12-19 17:18 UTC, smirolo commented on saas/mixins.py
> +    filter_backends = (DateRangeFilter, SearchFilter, OrderingFilter)
There is an `OrderingFilter` but there does not seem to be a default ordering provided.

2023-12-19 17:18 UTC, smirolo commented on saas/views/download.py
> +class BalancesMetricsDownloadView(CSVDownloadView, BalancesMetricsMixin):
Mixin should be before View (i.e. View is always the last class in the inheritance)

`class BalancesMetricsDownloadView(BalancesMetricsMixin, CSVDownloadView):`

2023-12-19 17:18 UTC, smirolo commented on saas/views/download.py
> +        consolidated_data = {}
What is the purpose of this code block? It looks like a duplicate of some code in the `retrieve_metrics` mixin.

2023-12-19 17:18 UTC, smirolo commented on saas/views/download.py
> +        self.set_plans_data(request)
I don't understand the purpose of the complexity here. Is it to define `self.plans`? In that case why not use a property?

```
@property
def plans(self):
    if not hasattr(self, '_plans'):
        self._plans = ...
    return self._plans
```

2023-12-19 17:18 UTC, smirolo commented on saas/views/download.py
> +        serializer = BalancesDueSerializer(decorated_queryset, many=True)
Why is the serialization happening in `get_queryset`? That doesn't seem the correct place to do it.

2023-12-19 17:18 UTC, smirolo commented on saas/views/download.py
> +        serializer = OrganizationSerializer(super().get_queryset(), many=True)
another serialization where it is not expected.

2023-12-19 17:18 UTC, smirolo commented on saas/api/metrics.py
> +    def calculate_date_periods(self, request):
Interesting introduction of `calculate_date_periods`. looks good!

2024-01-02 17:20 UTC, merged